### ISSUE TITLE
Filepath support

### ISSUE THREAD

**Issue by SevereOverfl0w** [prakashdanish/vim-zen#8]
As mention [here](https://www.reddit.com/r/vim/comments/8srosq/vimzen_a_barebones_vim_plugin_manager_that_does_3/e13eom1/)

**Comment by danishprakash** [comment]
@SevereOverfl0w this implementation does not manage the plugin since you are bound to do that yourself considering you are using a local version of a plugin or something you are developing yourself. All it does is adds it to the `rtp` and source the plugin files. Let me know if there is something that can be done to improve this.

**Comment by SevereOverfl0w** [comment]
I think this is perfect. All I want is to not have to touch anything separate to get my own plugins into vim!

**Comment by danishprakash** [comment]
Perfect, thanks for bringing this up.
